name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:
  should-run:
    runs-on: ubuntu-latest
    outputs:
      should-run: ${{ steps.check.outputs.should-run }}
    steps:
      - id: check
        run: |
          if [[ "${{ github.event_name }}" == "push" ]] || \
             [[ "${{ github.event.pull_request.merged }}" == "true" ]]; then
            echo "should-run=true" >> $GITHUB_OUTPUT
          else
            echo "should-run=false" >> $GITHUB_OUTPUT
          fi

  setup:
    needs: should-run
    if: needs.should-run.outputs.should-run == 'true'
    uses: ./.github/workflows/reusable-steps.yml

  lint:
    needs: [should-run, setup]
    if: needs.should-run.outputs.should-run == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Check code formatting
        run: ./gradlew ktlintCheck
        
      - name: Upload ktlint results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ktlint-report
          path: build/reports/ktlint/